devtools.tenant.inspector.enabled=true
devtools.tenant.normalizer.enabled=true
notifications.email.enabled=false
logging.level.org.springframework.security=INFO
logging.level.com.bharatshop=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=DEBUG