devtools.tenant.inspector.enabled=true
devtools.tenant.normalizer.enabled=true
notifications.email.enabled=false
logging.level.org.springframework.security=INFO
logging.level.com.bharatshop=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=DEBUG

# Maps Configuration
bharatshop.maps.provider=NOMINATIM
# bharatshop.maps.google.api-key=XXXX

# WhatsApp Configuration
notifications.whatsapp.enabled=true
notifications.whatsapp.api-url=https://graph.facebook.com/v22.0/993362360524447/messages
notifications.whatsapp.api-key=EAAMQm5Y7vZAUBQgXahjU3RN0DRhN1FnC9RgWRWeFyWqA17be1G8H7E5uWLWpcehauliZCXTZCFYdULzokNiPsyO9Fta2rJaK6Fqf2OCU6kOPO5gxruLUjuYqZBhE33uqZBz3H0ZCfwEyhMKZA3uqufjRgc3hnaC1ejpE5sKTKPPRH7aLECKlgXtkPEmCTkKI1pqAlwRjIUCjZApOTsFl1Dwrv5BBQNggzhCvMfZBZARcUE9I5ZB1MX14Gr4IBvcegRtJzYbbdPQdLlVoD7ikSZC2Q3FvRZAo5
notifications.whatsapp.sender-number=15551718906
